package com.dpad.mgr.core

import kotlinx.serialization.Serializable

/** One pad control the daemon can read (daemon source name, UI label, group). */
data class Source(val id: String, val label: String, val group: String)

object Sources {
    const val DPAD = "D-pad"
    const val FACE = "Face buttons"
    const val SHOULDER = "Shoulders / Triggers"
    const val BACK = "Back buttons"
    const val STICKS = "Sticks"
    const val MENU = "Menu"

    val ALL: List<Source> = listOf(
        Source("hat.up", "D-pad Up", DPAD),
        Source("hat.down", "D-pad Down", DPAD),
        Source("hat.left", "D-pad Left", DPAD),
        Source("hat.right", "D-pad Right", DPAD),
        Source("btn.south", "A (south)", FACE),
        Source("btn.east", "B (east)", FACE),
        Source("btn.north", "Y (north)", FACE),
        Source("btn.west", "X (west)", FACE),
        Source("btn.tl", "L1", SHOULDER),
        Source("btn.tr", "R1", SHOULDER),
        Source("btn.tl2", "L2 (button)", SHOULDER),
        Source("btn.tr2", "R2 (button)", SHOULDER),
        Source("lt", "L2 (trigger axis)", SHOULDER),
        Source("rt", "R2 (trigger axis)", SHOULDER),
        Source("btn.m1", "Back M1", BACK),
        Source("btn.m2", "Back M2", BACK),
        Source("ls.up", "Left stick Up", STICKS),
        Source("ls.down", "Left stick Down", STICKS),
        Source("ls.left", "Left stick Left", STICKS),
        Source("ls.right", "Left stick Right", STICKS),
        Source("rs.up", "Right stick Up", STICKS),
        Source("rs.down", "Right stick Down", STICKS),
        Source("rs.left", "Right stick Left", STICKS),
        Source("rs.right", "Right stick Right", STICKS),
        Source("btn.thumbl", "L3", STICKS),
        Source("btn.thumbr", "R3", STICKS),
        Source("btn.select", "Select / View", MENU),
        Source("btn.start", "Start / Menu", MENU),
        Source("btn.mode", "Home / Guide", MENU),
    )
    val GROUPS: List<String> = listOf(DPAD, FACE, SHOULDER, BACK, STICKS, MENU)
    val IDS: Set<String> = ALL.map { it.id }.toSet()
}

/** A key the user can pick: UI label <-> daemon KEY_ name. */
data class KeyDef(val label: String, val keyName: String, val other: Boolean = false)

object Keys {
    const val NONE = "NONE"

    val PRIMARY: List<KeyDef> = buildList {
        add(KeyDef("None", NONE))
        for (i in 1..12) add(KeyDef("F$i", "KEY_F$i"))
        for (i in 0..9) add(KeyDef("$i", "KEY_$i"))
        add(KeyDef("Up", "KEY_UP"))
        add(KeyDef("Down", "KEY_DOWN"))
        add(KeyDef("Left", "KEY_LEFT"))
        add(KeyDef("Right", "KEY_RIGHT"))
        add(KeyDef("Enter", "KEY_ENTER"))
        add(KeyDef("Space", "KEY_SPACE"))
        add(KeyDef("Esc", "KEY_ESC"))
        add(KeyDef("Wheel up", "WHEEL_UP"))
        add(KeyDef("Wheel down", "WHEEL_DOWN"))
    }
    val OTHER: List<KeyDef> = listOf(
        KeyDef("Wheel left", "HWHEEL_LEFT", other = true),
        KeyDef("Wheel right", "HWHEEL_RIGHT", other = true),
    ) + ('A'..'Z').map { KeyDef("$it", "KEY_$it", other = true) }
    val ALL: List<KeyDef> = PRIMARY + OTHER
    private val byName = ALL.associateBy { it.keyName }

    fun label(keyName: String?): String = if (keyName == null) "None" else (byName[keyName]?.label ?: keyName)
    fun isValid(keyName: String): Boolean = byName.containsKey(keyName)
}

@Serializable
data class Profile(
    val name: String,
    /** source id -> KEY_* name or "NONE". Missing entries mean NONE. */
    val map: Map<String, String> = emptyMap(),
    val deadzone: Float = 0.5f,
    val lsInvertY: Boolean = false,
    val rsInvertY: Boolean = false,
    /** source id of the btn.* control that acts as the modifier, or null for none. */
    val modifier: String? = null,
    /** source id -> KEY_ name, WHEEL_ target, or "NONE"; active only while [modifier] is held. Missing entries fall through to [map]. */
    val modBindings: Map<String, String> = emptyMap(),
    val wheelRepeatMs: Int = 120,
) {
    fun key(source: String): String = map[source] ?: Keys.NONE
    fun withKey(source: String, keyName: String): Profile = copy(map = map + (source to keyName))

    /** null = "same as base" (not present in modBindings). */
    fun modKey(source: String): String? = modBindings[source]
    fun withModKey(source: String, keyName: String?): Profile =
        copy(modBindings = if (keyName == null) modBindings - source else modBindings + (source to keyName))

    /** Exact daemon config text: source/target lines, deadzone, invert flags, mod+ layer, wheel repeat. */
    fun toConfigText(): String = buildString {
        append("# generated by Odin DPad Keys for profile \"").append(name.replace('\n', ' ')).append("\"\n")
        for (s in Sources.ALL) {
            val tgt = if (s.id == modifier) "MOD" else key(s.id).let { if (Keys.isValid(it)) it else Keys.NONE }
            append(s.id).append(' ').append(tgt).append('\n')
        }
        append("deadzone ").append(String.format(java.util.Locale.ROOT, "%.2f", deadzone.coerceIn(0.2f, 0.8f))).append('\n')
        append("ls.invert_y ").append(if (lsInvertY) 1 else 0).append('\n')
        append("rs.invert_y ").append(if (rsInvertY) 1 else 0).append('\n')
        if (modifier != null) {
            for (s in Sources.ALL) {
                if (s.id == modifier) continue
                val k = modBindings[s.id] ?: continue
                val tgt = if (Keys.isValid(k)) k else Keys.NONE
                append("mod+").append(s.id).append(' ').append(tgt).append('\n')
            }
        }
        append("wheel_repeat_ms ").append(wheelRepeatMs.coerceIn(60, 400)).append('\n')
    }

    companion object {
        val OSRS = Profile(
            name = "OSRS",
            map = mapOf(
                "hat.up" to "KEY_F1", "hat.down" to "KEY_F2", "hat.left" to "KEY_F3", "hat.right" to "KEY_F4",
                "ls.up" to "KEY_UP", "ls.down" to "KEY_DOWN", "ls.left" to "KEY_LEFT", "ls.right" to "KEY_RIGHT",
            ),
            deadzone = 0.5f,
            lsInvertY = true,
            modifier = "btn.thumbl",
            modBindings = mapOf(
                "ls.up" to "WHEEL_UP", "ls.down" to "WHEEL_DOWN",
                "ls.left" to "NONE", "ls.right" to "NONE",
            ),
            wheelRepeatMs = 120,
        )
        val WASD = Profile(
            name = "WASD",
            map = mapOf("hat.up" to "KEY_W", "hat.down" to "KEY_S", "hat.left" to "KEY_A", "hat.right" to "KEY_D"),
            deadzone = 0.5f,
        )
        val DEFAULTS = listOf(OSRS, WASD)
    }
}

@Serializable
data class AppData(
    val profiles: List<Profile> = Profile.DEFAULTS,
    /** package -> profile name. Absent = Off. */
    val assignments: Map<String, String> = emptyMap(),
) {
    fun profile(name: String?): Profile? = name?.let { n -> profiles.firstOrNull { it.name == n } }
    fun profileFor(pkg: String): Profile? = profile(assignments[pkg])
}
