#!/usr/bin/env bash
# gen_kl.sh <profile> - Generate a .kl file that remaps the Odin 2's D-pad to
# keyboard keys, based on the base layout the device is already using.
#
# profile: fkeys (UP->F1 DOWN->F2 LEFT->F3 RIGHT->F4)
#          wasd  (UP->W  DOWN->S  LEFT->A  RIGHT->D)
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

PROFILE="${1:-}"
case "$PROFILE" in
  fkeys) UP=F1; DOWN=F2; LEFT=F3; RIGHT=F4 ;;
  wasd)  UP=W;  DOWN=S;  LEFT=A;  RIGHT=D ;;
  *) die "Usage: $0 <fkeys|wasd>" ;;
esac

[[ -f "$SCRIPT_DIR/device.env" ]] || die "device.env not found. Run ./investigate.sh baseline (or ./probe.sh) first."
# shellcheck source=/dev/null
source "$SCRIPT_DIR/device.env"

: "${VID:?device.env missing VID}"
: "${PID:?device.env missing PID}"
: "${DPAD_MODE:?device.env missing DPAD_MODE}"
VERSION="${VERSION:-0000}"

if [[ "$DPAD_MODE" == "hat" ]]; then
  die "This device reports the D-pad only as ABS hat axes (ABS_HAT0X/ABS_HAT0Y).
A key layout (.kl) file can only map keys (scancode -> KEYCODE); it cannot
turn an analog/hat axis into a key event. Remapping this D-pad to keyboard
keys is not possible via a .kl file for this device. (Consider an
InputEventReader/Kernel-level remap or a gamepad-to-keyboard app instead.)"
fi
if [[ "$DPAD_MODE" == "none" ]]; then
  die "device.env reports DPAD_MODE=none - no recognizable D-pad reporting was
found for this device during probing. Re-run ./probe.sh --watch and press the
D-pad to see what it actually sends, then update device.env by hand if needed."
fi

require_adb_device

FILENAME="Vendor_${VID}_Product_${PID}.kl"
mkdir -p "$SCRIPT_DIR/base" "$SCRIPT_DIR/profiles/$PROFILE"

# The OUTPUT filename is version-qualified when possible: InputDevice.cpp
# tries Vendor_%04x_Product_%04x_Version_%04x.kl across ALL keylayout search
# dirs before it tries the unversioned name in any of them, so a
# version-qualified file dropped in /data/system/devices/keylayout wins
# everywhere without needing a partition overlay. Version must be non-zero.
VERSION_LC="${VERSION,,}"
if [[ -n "$VERSION_LC" && "$VERSION_LC" != "0000" ]]; then
  OUT_FILENAME="Vendor_${VID}_Product_${PID}_Version_${VERSION_LC}.kl"
else
  warn "device.env VERSION is unset/0000; falling back to the unversioned filename."
  warn "This file can be shadowed by a same-named stock file in /odm, /vendor,"
  warn "/product, /system_ext, or /system - re-run investigate.sh baseline (as"
  warn "root) to capture a real VERSION if that turns out to be a problem."
  OUT_FILENAME="$FILENAME"
fi

BASE_LOCAL=""

# --- 1. try to read the KeyLayoutFile path dumpsys reports for this device ---
info "Looking up the active key layout file via dumpsys input ..."
DUMP_PATH="$(adb shell dumpsys input 2>/dev/null | tr -d '\r' | grep -A30 -i "$DEV_NAME" \
  | grep -i 'KeyLayoutFile' | head -n1 | sed -n 's/.*KeyLayoutFile:[[:space:]]*//p')"

if [[ -n "$DUMP_PATH" ]]; then
  info "dumpsys reports active layout: $DUMP_PATH"
  BASE_NAME="$(basename "$DUMP_PATH")"
  if adb pull "$DUMP_PATH" "$SCRIPT_DIR/base/$BASE_NAME" >/dev/null 2>&1; then
    BASE_LOCAL="$SCRIPT_DIR/base/$BASE_NAME"
  else
    warn "adb pull of $DUMP_PATH failed; will try the standard search paths instead."
  fi
fi

# --- 2. fall back: search the five standard dirs for our vendor/product file ---
if [[ -z "$BASE_LOCAL" ]]; then
  info "Searching standard keylayout directories for $FILENAME ..."
  for dir in /odm/usr/keylayout /vendor/usr/keylayout /product/usr/keylayout /system/usr/keylayout /data/system/devices/keylayout; do
    REMOTE="$dir/$FILENAME"
    if adb shell "[ -f $REMOTE ] && echo FOUND" 2>/dev/null | grep -q FOUND; then
      info "Found $REMOTE"
      if adb pull "$REMOTE" "$SCRIPT_DIR/base/$FILENAME" >/dev/null 2>&1; then
        BASE_LOCAL="$SCRIPT_DIR/base/$FILENAME"
        break
      fi
    fi
  done
fi

# --- 3. final fallback: Generic.kl ---
if [[ -z "$BASE_LOCAL" ]]; then
  warn "No vendor-specific .kl found on device; falling back to /system/usr/keylayout/Generic.kl"
  if adb pull /system/usr/keylayout/Generic.kl "$SCRIPT_DIR/base/Generic.kl" >/dev/null 2>&1; then
    BASE_LOCAL="$SCRIPT_DIR/base/Generic.kl"
  else
    die "Could not pull any base .kl file (not even Generic.kl) from the device."
  fi
fi

info "Using base layout: $BASE_LOCAL"

OUT="$SCRIPT_DIR/profiles/$PROFILE/$OUT_FILENAME"

case "$DPAD_MODE" in
  buttons)
    UP_CODE=544; DOWN_CODE=545; LEFT_CODE=546; RIGHT_CODE=547 ;; # BTN_DPAD_UP/DOWN/LEFT/RIGHT
  arrows)
    UP_CODE=103; DOWN_CODE=108; LEFT_CODE=105; RIGHT_CODE=106 ;; # KEY_UP/DOWN/LEFT/RIGHT
  *)
    die "Unexpected DPAD_MODE=$DPAD_MODE" ;;
esac

{
  echo "# generated by odin2-dpad-kl profile=$PROFILE base=$(basename "$BASE_LOCAL")"
  awk \
    -v up_code="$UP_CODE" -v down_code="$DOWN_CODE" -v left_code="$LEFT_CODE" -v right_code="$RIGHT_CODE" \
    -v up_name="$UP" -v down_name="$DOWN" -v left_name="$LEFT" -v right_name="$RIGHT" \
    -f "$SCRIPT_DIR/lib/rewrite_dpad.awk" "$BASE_LOCAL"
} > "$OUT"

info "Wrote $OUT"
echo
info "Diff against base ($DPAD_MODE mode, profile=$PROFILE):"
diff -u "$BASE_LOCAL" "$OUT" || true
