#!/usr/bin/env bash
# investigate.sh - read-only(*) device investigation toolkit for the AYN
# Odin 2 Portal (Android 13), used to figure out how the built-in D-pad is
# reported, which .kl file Android resolves for it, and whether we can force
# a reload without Magisk/reboot.
#
# (*) Everything is read-only on the device except: logcat/dmesg buffer
# clears (toggle-test) and the driver unbind/bind in reload-test (which is
# gated behind --yes and only rebinds the pad's own driver).
#
# All root commands go through `adb shell su -c "..."` via lib/common.sh's
# su_run/have_su, and degrade gracefully (warn + continue) if su is
# unavailable.
#
# Usage:
#   ./investigate.sh baseline
#   ./investigate.sh scan <label>
#   ./investigate.sh snap <label>
#   ./investigate.sh diff <label1> <label2>
#   ./investigate.sh toggle-test
#   ./investigate.sh reload-test [--yes]
#   ./investigate.sh report
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck source=lib/reload.sh
source "$SCRIPT_DIR/lib/reload.sh"

CAPTURE_DIR="$SCRIPT_DIR/capture"
mkdir -p "$CAPTURE_DIR"

KEYLAYOUT_DIRS_NOROOT="/odm/usr/keylayout /vendor/usr/keylayout /product/usr/keylayout /system_ext/usr/keylayout /system/usr/keylayout"
KEYLAYOUT_DIR_ROOT="/data/system/devices/keylayout"

# --- shared capture helpers --------------------------------------------

# capture_getevent_i <out_file>
capture_getevent_i() {
  adb shell getevent -i 2>/dev/null | tr -d '\r' > "$1"
}

# capture_getevent_lp <out_file>
capture_getevent_lp() {
  adb shell getevent -lp 2>/dev/null | tr -d '\r' > "$1"
}

# capture_dumpsys_input <out_file>
capture_dumpsys_input() {
  adb shell dumpsys input 2>/dev/null | tr -d '\r' > "$1"
}

# capture_keylayouts <out_file>
capture_keylayouts() {
  {
    echo "=== ls -lR (non-root dirs) ==="
    adb shell ls -lR --time-style=full-iso $KEYLAYOUT_DIRS_NOROOT 2>/dev/null
    echo
    echo "=== ls -lR $KEYLAYOUT_DIR_ROOT (root) ==="
    su_run "ls -lR --time-style=full-iso $KEYLAYOUT_DIR_ROOT" || echo "(su unavailable or dir missing)"
  } > "$1"
  echo "Vendor_2020_* files found:"
  grep -i 'Vendor_2020_' "$1" || echo "  (none)"
}

# capture_getprop <out_file>
capture_getprop() {
  adb shell getprop 2>/dev/null | tr -d '\r' > "$1"
}

# capture_settings <out_dir_prefix>  (writes <prefix>_global.txt/_system.txt/_secure.txt)
capture_settings() {
  local prefix="$1"
  adb shell settings list global 2>/dev/null | tr -d '\r' > "${prefix}_global.txt"
  adb shell settings list system 2>/dev/null | tr -d '\r' > "${prefix}_system.txt"
  adb shell settings list secure 2>/dev/null | tr -d '\r' > "${prefix}_secure.txt"
}

# capture_proc_input_devices <out_file>
capture_proc_input_devices() {
  adb shell cat /proc/bus/input/devices 2>/dev/null | tr -d '\r' > "$1"
}

# select_pad_line <parsed_text>  - echoes the chosen device line, same
# heuristic as probe.sh: prefer a device whose name matches
# odin|ayn|gamepad|controller AND has D-pad-shaped capabilities; fall back to
# either match alone.
select_pad_line() {
  local parsed="$1"
  local name_re='odin|ayn|gamepad|controller'
  local best="" fallback_name="" fallback_caps=""
  local line name has_btndpad has_btna name_match caps_match
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    name="$(echo "$line" | sed -n 's/.*NAME:\([^|]*\).*/\1/p')"
    has_btndpad="$(echo "$line" | sed -n 's/.*HAS_BTNDPAD:\([01]\).*/\1/p')"
    has_btna="$(echo "$line" | sed -n 's/.*HAS_BTNA:\([01]\).*/\1/p')"
    name_match=0; echo "$name" | grep -Eiq "$name_re" && name_match=1
    caps_match=0; [[ "$has_btndpad" == "1" || "$has_btna" == "1" ]] && caps_match=1
    if [[ -z "$best" && $name_match -eq 1 && $caps_match -eq 1 ]]; then best="$line"; fi
    if [[ -z "$fallback_name" && $name_match -eq 1 ]]; then fallback_name="$line"; fi
    if [[ -z "$fallback_caps" && $caps_match -eq 1 ]]; then fallback_caps="$line"; fi
  done <<< "$parsed"
  echo "${best:-${fallback_name:-$fallback_caps}}"
}

# write_device_env - writes the same VAR=value content to both
# $CAPTURE_DIR/device.env and $SCRIPT_DIR/device.env (root), so gen_kl.sh /
# install_profile.sh (which source the root file) and scan/diff/report
# (which source the capture copy) stay in sync.
write_device_env() {
  local content
  content="$(cat <<ENVEOF
# Generated by investigate.sh baseline on $(date -u +%Y-%m-%dT%H:%M:%SZ)
EVENT_NODE=$EVENT_NODE
DEV_NAME="$DEV_NAME"
VID=$VID
PID=$PID
VERSION=${VERSION:-0000}
BUSTYPE=${BUSTYPE:-unknown}
DRIVER_PATH="${DRIVER_PATH:-}"
DPAD_MODE=$DPAD_MODE
KL_RESOLVED="${KL_RESOLVED:-}"
PSERVERBINDER=${PSERVERBINDER:-UNKNOWN}
RETRO_NAME="${RETRO_NAME:-}"
OTA_VERSION="${OTA_VERSION:-}"
ANDROID_RELEASE="${ANDROID_RELEASE:-}"
BUILD_ID="${BUILD_ID:-}"
ENVEOF
)"
  printf '%s\n' "$content" > "$CAPTURE_DIR/device.env"
  printf '%s\n' "$content" > "$SCRIPT_DIR/device.env"
}

bustype_english() {
  case "$1" in
    0003|03) echo "USB" ;;
    0005|05) echo "Bluetooth" ;;
    0019|19) echo "host/platform" ;;
    0018|18) echo "i2c" ;;
    *) echo "unknown (0x$1)" ;;
  esac
}

# --- subcommands ---------------------------------------------------------

cmd_baseline() {
  require_adb_device

  info "Capturing getevent -i / -lp ..."
  capture_getevent_i "$CAPTURE_DIR/getevent_i.txt"
  capture_getevent_lp "$CAPTURE_DIR/getevent_lp.txt"

  PARSED="$(awk -f "$SCRIPT_DIR/lib/parse_getevent.awk" "$CAPTURE_DIR/getevent_i.txt")"
  [[ -n "$PARSED" ]] || die "Could not parse any input devices from getevent -i output."

  CHOSEN="$(select_pad_line "$PARSED")"
  [[ -n "$CHOSEN" ]] || die "No candidate gamepad device found in getevent -i output."

  EVENT_NODE="$(echo "$CHOSEN" | sed -n 's/.*EVENT:\([^|]*\).*/\1/p')"
  DEV_NAME="$(echo "$CHOSEN" | sed -n 's/.*NAME:\([^|]*\).*/\1/p')"
  VID="$(norm_hex4 "$(echo "$CHOSEN" | sed -n 's/.*VENDOR:\([^|]*\).*/\1/p')")"
  PID="$(norm_hex4 "$(echo "$CHOSEN" | sed -n 's/.*PRODUCT:\([^|]*\).*/\1/p')")"
  HAS_BTNDPAD="$(echo "$CHOSEN" | sed -n 's/.*HAS_BTNDPAD:\([01]\).*/\1/p')"
  HAS_ARROWS="$(echo "$CHOSEN" | sed -n 's/.*HAS_ARROWS:\([01]\).*/\1/p')"
  HAS_HAT="$(echo "$CHOSEN" | sed -n 's/.*HAS_HAT:\([01]\).*/\1/p')"
  if [[ "$HAS_BTNDPAD" == "1" ]]; then DPAD_MODE=buttons
  elif [[ "$HAS_ARROWS" == "1" ]]; then DPAD_MODE=arrows
  elif [[ "$HAS_HAT" == "1" ]]; then DPAD_MODE=hat
  else DPAD_MODE=none
  fi

  info "Selected device: $EVENT_NODE \"$DEV_NAME\" vendor=0x$VID product=0x$PID DPAD_MODE=$DPAD_MODE"

  local evn_base="$(basename "$EVENT_NODE")"
  VERSION="$(su_run "cat /sys/class/input/$evn_base/device/id/version" || true)"
  VERSION="$(echo "${VERSION:-}" | tr -d '\r\n ')"
  VERSION="$(norm_hex4 "${VERSION:-0}" 2>/dev/null || echo 0000)"
  BUSTYPE_RAW="$(su_run "cat /sys/class/input/$evn_base/device/id/bustype" || true)"
  BUSTYPE_RAW="$(echo "${BUSTYPE_RAW:-}" | tr -d '\r\n ')"
  BUSTYPE="${BUSTYPE_RAW:-unknown}"
  DRIVER_PATH="$(su_run "readlink -f /sys/class/input/$evn_base/device" || true)"
  DRIVER_PATH="$(echo "${DRIVER_PATH:-}" | tr -d '\r\n')"

  echo "    id/version : ${VERSION:-unknown}"
  echo "    id/bustype : ${BUSTYPE:-unknown} ($(bustype_english "$BUSTYPE"))"
  echo "    driver path: ${DRIVER_PATH:-unknown}"
  info "Pad bus: $(bustype_english "$BUSTYPE"); USB/driver interface path: ${DRIVER_PATH:-unknown}"

  info "Capturing dumpsys input ..."
  capture_dumpsys_input "$CAPTURE_DIR/dumpsys_input.txt"
  local block
  block="$(grep -A30 -iF "$DEV_NAME" "$CAPTURE_DIR/dumpsys_input.txt" || true)"
  echo "$block" | grep -iE 'KeyLayoutFile|KeyCharacterMapFile|Version|Sources|Location|ControllerNumber|Descriptor' || warn "No dumpsys input block matched \"$DEV_NAME\""
  KL_RESOLVED="$(echo "$block" | grep -i 'KeyLayoutFile' | head -n1 | sed -n 's/.*KeyLayoutFile:[[:space:]]*//p')"
  if [[ -n "$KL_RESOLVED" ]]; then
    info "Android RESOLVED KeyLayoutFile: $KL_RESOLVED"
  else
    warn "Could not determine the resolved KeyLayoutFile from dumpsys input."
  fi

  info "Listing keylayout directories ..."
  capture_keylayouts "$CAPTURE_DIR/keylayouts.txt"

  info "Listing AYN/Odin packages ..."
  adb shell pm list packages -f 2>/dev/null | tr -d '\r' | grep -iE 'ayn|odin|gameassistant|retrostation' > "$CAPTURE_DIR/ayn_pkgs.txt" || true
  if [[ -s "$CAPTURE_DIR/ayn_pkgs.txt" ]]; then
    cat "$CAPTURE_DIR/ayn_pkgs.txt"
    while IFS= read -r line; do
      local pkg
      pkg="$(echo "$line" | sed 's/.*=//')"
      [[ -n "$pkg" ]] || continue
      adb shell dumpsys package "$pkg" 2>/dev/null | tr -d '\r' > "$CAPTURE_DIR/pkg_${pkg}.txt" || true
    done < "$CAPTURE_DIR/ayn_pkgs.txt"
  else
    warn "No AYN/Odin/GameAssistant/RetroStation packages found."
  fi

  info "Checking for AYN PServerBinder root service ..."
  if adb shell service list 2>/dev/null | tr -d '\r' | grep -qi PServerBinder; then
    PSERVERBINDER=FOUND
  else
    PSERVERBINDER="NOT FOUND"
  fi
  echo "    PServerBinder: $PSERVERBINDER"
  RETRO_NAME="$(adb shell getprop ro.vendor.retro.name 2>/dev/null | tr -d '\r')"
  OTA_VERSION="$(adb shell getprop ro.build.odin2.ota.version 2>/dev/null | tr -d '\r')"
  ANDROID_RELEASE="$(adb shell getprop ro.build.version.release 2>/dev/null | tr -d '\r')"
  BUILD_ID="$(adb shell getprop ro.build.display.id 2>/dev/null | tr -d '\r')"
  echo "    ro.vendor.retro.name       : $RETRO_NAME"
  echo "    ro.build.odin2.ota.version : $OTA_VERSION"
  echo "    ro.build.version.release   : $ANDROID_RELEASE"
  echo "    ro.build.display.id        : $BUILD_ID"

  info "AYN controller-style settings keys (settings list system) ..."
  adb shell settings list system 2>/dev/null | tr -d '\r' \
    | grep -iE 'abxy|flip_button|gamepad|trigger_input|remap_custom|app_whiteList' | tee "$CAPTURE_DIR/settings_ayn_keys.txt" \
    || warn "No matching settings keys found."

  info "uinput availability / SELinux mode ..."
  su_run "ls -l /dev/uinput" || warn "Could not stat /dev/uinput (su unavailable or node missing)."
  adb shell getenforce 2>/dev/null || true

  info "Capturing /proc/bus/input/devices ..."
  capture_proc_input_devices "$CAPTURE_DIR/proc_input_devices.txt"

  write_device_env
  info "Wrote $CAPTURE_DIR/device.env and $SCRIPT_DIR/device.env"
}

cmd_scan() {
  local label="${1:-}"
  [[ -n "$label" ]] || die "Usage: $0 scan <label>"
  [[ -f "$CAPTURE_DIR/device.env" ]] || die "capture/device.env not found. Run '$0 baseline' first."
  # shellcheck source=/dev/null
  source "$CAPTURE_DIR/device.env"
  : "${EVENT_NODE:?device.env missing EVENT_NODE}"
  require_adb_device

  echo
  echo "Press A, then B, then D-pad Up, Down, Left, Right, one at a time, within 10 seconds."
  echo "(Capturing from $EVENT_NODE ...)"
  local out="$CAPTURE_DIR/scan_${label}.txt"
  timeout 12 adb shell getevent -lt "$EVENT_NODE" > "$out" 2>/dev/null || true
  info "Wrote $out"

  echo "EV_KEY / EV_ABS codes seen:"
  grep -E 'EV_KEY|EV_ABS' "$out" | awk '{print $3, $4}' | sort -u || echo "  (none captured)"
}

cmd_snap() {
  local label="${1:-}"
  [[ -n "$label" ]] || die "Usage: $0 snap <label>"
  require_adb_device
  local dir="$CAPTURE_DIR/$label"
  mkdir -p "$dir"

  info "Snapshotting to $dir/ ..."
  capture_getevent_i "$dir/getevent_i.txt"
  capture_dumpsys_input "$dir/dumpsys_input.txt"
  capture_keylayouts "$dir/keylayouts.txt" > /dev/null
  capture_getprop "$dir/getprop.txt"
  capture_settings "$dir/settings"
  capture_proc_input_devices "$dir/proc_input_devices.txt"
  info "Snapshot '$label' complete."
}

cmd_diff() {
  local l1="${1:-}" l2="${2:-}"
  [[ -n "$l1" && -n "$l2" ]] || die "Usage: $0 diff <label1> <label2>"
  local d1="$CAPTURE_DIR/$l1" d2="$CAPTURE_DIR/$l2"
  [[ -d "$d1" ]] || die "$d1 not found. Run '$0 snap $l1' first."
  [[ -d "$d2" ]] || die "$d2 not found. Run '$0 snap $l2' first."

  local any_diff=0 f base d
  while IFS= read -r -d '' f; do
    base="$(basename "$f")"
    if [[ -f "$d2/$base" ]]; then
      d="$(diff -u "$f" "$d2/$base" || true)"
      if [[ -n "$d" ]]; then
        any_diff=1
        echo "=== $base ==="
        echo "$d"
        echo
      fi
    fi
  done < <(find "$d1" -maxdepth 1 -type f -print0)

  [[ "$any_diff" -eq 0 ]] && info "No differences found between '$l1' and '$l2'."

  cat <<'EOF'

Decision rules:
  - scancodes differ between scan_xbox and scan_odin  -> MCU/PID mechanism
    (the pad itself reports different HID scancodes per controller style).
  - KeyLayoutFile path or mtime changed                -> .kl swap
    (Android picked a different key layout file, or the same file's content
    changed).
  - nothing changed but settings keys flipped           -> framework remap
    (expected keys: temp_abxy_layout_mode / flip_button_layout - AYN's own
    app is remapping in software, not at the input-device level).
EOF
}

cmd_toggle_test() {
  require_adb_device
  info "Clearing logcat and dmesg buffers ..."
  adb logcat -b all -c 2>/dev/null || true
  su_run "dmesg -C" || warn "Could not clear dmesg (su unavailable)."

  cmd_snap before
  cmd_scan odin

  echo
  echo ">>> In the slide-out, switch Controller Style to Xbox now, then press Enter."
  read -r -p "Press Enter when done: " _

  cmd_snap after
  cmd_scan xbox

  info "Dumping filtered logcat ..."
  adb logcat -b all -d 2>/dev/null | tr -d '\r' \
    | grep -iE 'input|eventhub|inputreader|ayn|odin|gamepad|usb|hid' > "$CAPTURE_DIR/logcat_toggle.txt" || true
  info "Wrote $CAPTURE_DIR/logcat_toggle.txt"

  info "Dumping dmesg (root) ..."
  su_run "dmesg" > "$CAPTURE_DIR/dmesg_toggle.txt" || warn "Could not capture dmesg (su unavailable)."
  if [[ -s "$CAPTURE_DIR/dmesg_toggle.txt" ]]; then
    grep -i 'usb disconnect' "$CAPTURE_DIR/dmesg_toggle.txt" && info "Found USB disconnect in dmesg (points to MCU/PID re-enumeration)." || true
  fi

  cmd_diff before after

  echo
  echo ">>> Please switch Controller Style back now."
  read -r -p "Press Enter once reverted: " _
}

cmd_reload_test() {
  local yes=0
  for arg in "$@"; do
    case "$arg" in
      --yes) yes=1 ;;
      *) die "Unknown argument: $arg" ;;
    esac
  done
  [[ "$yes" -eq 1 ]] || die "reload-test will drop the pad for ~1s. Re-run with --yes to confirm."

  require_adb_device
  [[ -f "$CAPTURE_DIR/device.env" ]] || die "capture/device.env not found. Run '$0 baseline' first."
  # shellcheck source=/dev/null
  source "$CAPTURE_DIR/device.env"
  : "${DEV_NAME:?device.env missing DEV_NAME}"
  : "${VID:?device.env missing VID}"
  : "${PID:?device.env missing PID}"
  : "${DRIVER_PATH:?device.env missing DRIVER_PATH - re-run baseline with su available}"

  warn "=============================================================="
  warn " About to unbind/rebind the pad's driver. It WILL disappear   "
  warn " for roughly 1 second. Proceeding because --yes was given.    "
  warn "=============================================================="

  local before_count
  before_count="$(adb shell dumpsys input 2>/dev/null | tr -d '\r' | grep -c -iF "$DEV_NAME" || true)"
  info "dumpsys input mentions of \"$DEV_NAME\" before reload: $before_count"

  if reload_device "$DRIVER_PATH" "$VID" "$PID"; then
    info "Reload succeeded in ${RELOAD_ELAPSED}s; new event node: $NEW_EVENT_NODE"
    local after_dump block kl
    after_dump="$(adb shell dumpsys input 2>/dev/null | tr -d '\r')"
    block="$(echo "$after_dump" | grep -A30 -iF "$DEV_NAME" || true)"
    kl="$(echo "$block" | grep -i 'KeyLayoutFile' | head -n1)"
    if [[ -n "$kl" ]]; then
      info "Post-reload dumpsys input: $kl"
    else
      warn "Could not find a dumpsys input block for \"$DEV_NAME\" after reload."
    fi
  else
    die "Reload did not succeed - see warnings above."
  fi
}

cmd_report() {
  [[ -f "$CAPTURE_DIR/device.env" ]] || die "capture/device.env not found. Run '$0 baseline' first."
  echo "=== capture/device.env ==="
  cat "$CAPTURE_DIR/device.env"
  echo
  # shellcheck source=/dev/null
  source "$CAPTURE_DIR/device.env"
  echo "=== summary ==="
  echo "Pad          : ${DEV_NAME:-unknown} (${EVENT_NODE:-unknown})"
  echo "VID:PID      : ${VID:-????}:${PID:-????}  Version: ${VERSION:-0000}  Bus: $(bustype_english "${BUSTYPE:-}")"
  echo "DPAD_MODE    : ${DPAD_MODE:-unknown}"
  echo "KL_RESOLVED  : ${KL_RESOLVED:-unknown}"
  echo "DRIVER_PATH  : ${DRIVER_PATH:-unknown}"
  echo "PServerBinder: ${PSERVERBINDER:-UNKNOWN}"
  echo "Android      : ${ANDROID_RELEASE:-?} (${BUILD_ID:-?}), OTA ${OTA_VERSION:-?}, retro.name=${RETRO_NAME:-?}"
}

# --- dispatch --------------------------------------------------------------

CMD="${1:-}"
[[ $# -gt 0 ]] && shift

case "$CMD" in
  baseline)    cmd_baseline "$@" ;;
  scan)        cmd_scan "$@" ;;
  snap)        cmd_snap "$@" ;;
  diff)        cmd_diff "$@" ;;
  toggle-test) cmd_toggle_test "$@" ;;
  reload-test) cmd_reload_test "$@" ;;
  report)      cmd_report "$@" ;;
  *) die "Usage: $0 <baseline|scan <label>|snap <label>|diff <l1> <l2>|toggle-test|reload-test [--yes]|report>" ;;
esac
