#!/usr/bin/env bash
# probe.sh - Discover the Odin 2 built-in gamepad's vendor/product id and D-pad
# reporting mode (buttons / arrow-keys / hat-axes / none), and write device.env
# for the other scripts in this toolkit to consume.
#
# Usage: ./probe.sh [--watch]
#   --watch   after identifying the device, stream raw events from it
#             (adb shell getevent -lt <node>) so you can confirm behavior by
#             pressing the D-pad. Ctrl-C to stop.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

WATCH=0
for arg in "$@"; do
  case "$arg" in
    --watch) WATCH=1 ;;
    *) die "Unknown argument: $arg (only --watch is supported)" ;;
  esac
done

require_adb_device

info "Running 'adb shell getevent -i' ..."
RAW="$(adb shell getevent -i 2>/dev/null | tr -d '\r')"

if [[ -z "$RAW" ]]; then
  die "getevent -i returned nothing. Is the device connected and unlocked?"
fi

PARSED="$(printf '%s\n' "$RAW" | awk -f "$SCRIPT_DIR/lib/parse_getevent.awk")"

if [[ -z "$PARSED" ]]; then
  die "Could not parse any input devices from getevent -i output."
fi

info "Devices found:"
echo "$PARSED" | while IFS= read -r line; do
  ev="$(echo "$line" | sed -n 's/.*EVENT:\([^|]*\).*/\1/p')"
  name="$(echo "$line" | sed -n 's/.*NAME:\([^|]*\).*/\1/p')"
  echo "  $ev  \"$name\""
done

# --- pick the best candidate --------------------------------------------
NAME_RE='odin|ayn|gamepad|controller'

best_line=""
fallback_name_only=""
fallback_caps_only=""

while IFS= read -r line; do
  name="$(echo "$line" | sed -n 's/.*NAME:\([^|]*\).*/\1/p')"
  has_btndpad="$(echo "$line" | sed -n 's/.*HAS_BTNDPAD:\([01]\).*/\1/p')"
  has_btna="$(echo "$line" | sed -n 's/.*HAS_BTNA:\([01]\).*/\1/p')"

  name_match=0
  if echo "$name" | grep -Eiq "$NAME_RE"; then name_match=1; fi

  caps_match=0
  if [[ "$has_btndpad" == "1" || "$has_btna" == "1" ]]; then caps_match=1; fi

  if [[ -z "$best_line" && $name_match -eq 1 && $caps_match -eq 1 ]]; then
    best_line="$line"
  fi
  if [[ -z "$fallback_name_only" && $name_match -eq 1 ]]; then
    fallback_name_only="$line"
  fi
  if [[ -z "$fallback_caps_only" && $caps_match -eq 1 ]]; then
    fallback_caps_only="$line"
  fi
done <<< "$PARSED"

CHOSEN="${best_line:-${fallback_name_only:-$fallback_caps_only}}"

if [[ -z "$CHOSEN" ]]; then
  die "No candidate gamepad device found (looked for name matching /$NAME_RE/i or KEY caps 0x130/0x220)."
fi

EVENT_NODE="$(echo "$CHOSEN" | sed -n 's/.*EVENT:\([^|]*\).*/\1/p')"
DEV_NAME="$(echo "$CHOSEN" | sed -n 's/.*NAME:\([^|]*\).*/\1/p')"
VENDOR_RAW="$(echo "$CHOSEN" | sed -n 's/.*VENDOR:\([^|]*\).*/\1/p')"
PRODUCT_RAW="$(echo "$CHOSEN" | sed -n 's/.*PRODUCT:\([^|]*\).*/\1/p')"
HAS_BTNDPAD="$(echo "$CHOSEN" | sed -n 's/.*HAS_BTNDPAD:\([01]\).*/\1/p')"
HAS_ARROWS="$(echo "$CHOSEN" | sed -n 's/.*HAS_ARROWS:\([01]\).*/\1/p')"
HAS_HAT="$(echo "$CHOSEN" | sed -n 's/.*HAS_HAT:\([01]\).*/\1/p')"

VID="$(norm_hex4 "$VENDOR_RAW")"
PID="$(norm_hex4 "$PRODUCT_RAW")"

if [[ "$HAS_BTNDPAD" == "1" ]]; then
  DPAD_MODE=buttons
elif [[ "$HAS_ARROWS" == "1" ]]; then
  DPAD_MODE=arrows
elif [[ "$HAS_HAT" == "1" ]]; then
  DPAD_MODE=hat
else
  DPAD_MODE=none
fi

echo
info "Selected device:"
echo "    event node : $EVENT_NODE"
echo "    name       : $DEV_NAME"
echo "    vendor     : 0x$VID"
echo "    product    : 0x$PID"
echo "    BTN_DPAD_*  (0x220-0x223) present : $HAS_BTNDPAD"
echo "    KEY_UP/DOWN/LEFT/RIGHT (103/108/105/106) present : $HAS_ARROWS"
echo "    ABS hat axes (0x10/0x11) present : $HAS_HAT"
echo "    DPAD_MODE  : $DPAD_MODE"

if [[ "$DPAD_MODE" == "hat" ]]; then
  warn "This device only reports the D-pad as ABS hat axes. A .kl file cannot"
  warn "turn axes into keys - gen_kl.sh will refuse to proceed for this device."
elif [[ "$DPAD_MODE" == "none" ]]; then
  warn "Could not find any recognizable D-pad reporting (buttons, arrow keys, or hat axes)."
  warn "Try --watch and press the D-pad to see what codes it actually sends."
fi

cat > "$SCRIPT_DIR/device.env" <<ENVEOF
# Generated by probe.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
EVENT_NODE=$EVENT_NODE
DEV_NAME="$DEV_NAME"
VID=$VID
PID=$PID
DPAD_MODE=$DPAD_MODE
ENVEOF
info "Wrote $SCRIPT_DIR/device.env"

# --- report which stock .kl files exist for this vid/pid ----------------
echo
info "Searching stock keylayout dirs for Vendor_${VID}_Product_${PID}.kl ..."
adb shell ls -l /odm/usr/keylayout /vendor/usr/keylayout /product/usr/keylayout /system/usr/keylayout /data/system/devices/keylayout 2>/dev/null \
  | grep -i "Vendor_${VID}_Product_${PID}" || echo "  (no matching file found in the standard search paths)"

echo
info "dumpsys input details for \"$DEV_NAME\":"
adb shell dumpsys input 2>/dev/null | grep -A30 -i "$DEV_NAME" | grep -iE 'KeyLayoutFile|KeyCharacterMapFile|Sources|Location|ControllerNum' \
  || echo "  (no matching dumpsys input block found)"

if [[ "$WATCH" -eq 1 ]]; then
  echo
  info "Watching raw events from $EVENT_NODE - press D-pad directions now. Ctrl-C to stop."
  adb shell getevent -lt "$EVENT_NODE"
fi
